[gc]
command = 'git commit -m "#CURSOR"'
description = "Start a Git commit"

[sq]
command = '"#COMMAND"'
description = "Surround with quotes"
insert_type = "Surround"

[ga]
command = "git add ."
description = "Git add all"
execute = true

[id]
command = "date +%Y%m%d"
description = "Insert current date in YYYYMMDD format"
insert_type = "Insert"
evaluate = true

[ps]
command = "sudo "
description = "Prepend sudo"
insert_type = "Prepend"

[gs]
command = "git status"
description = "Git status"
execute = true

[y]
command = " | xclip -selection clipboard"
description = "Append copy to clipboard"
insert_type = "Append"
